# -*- coding: utf-8 -*-
"""UAS2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17f4bgyuGo-vjGqMV37JdnCr6_Qd-HbT4
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# Load gambar
image = cv2.imread('/content/kambing.jpg')
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)  # Konversi ke RGB

# Ubah bentuk gambar menjadi array 2D (N, 3)
pixels = image.reshape((-1, 3))

# Terapkan K-Means dengan k=3 (jumlah segmen)
k = 3
kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
kmeans.fit(pixels)

# Ambil label dan centroid warna
labels = kmeans.labels_
centroids = np.uint8(kmeans.cluster_centers_)

# Bentuk ulang hasil clustering ke dimensi gambar asli
segmented_image = centroids[labels].reshape(image.shape)

# Tampilkan hasil
fig, ax = plt.subplots(1, 2, figsize=(10, 5))
ax[0].imshow(image)
ax[0].set_title("Gambar Asli")
ax[0].axis("off")

ax[1].imshow(segmented_image)
ax[1].set_title("Segmentasi K-Means")
ax[1].axis("off")

plt.show()